# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true

# Setup
title: QuantStack
description: 'The QuantStack Website'
url: http://quantstack.net

social:
  - icon: twitter
    url: https://twitter.com/QuantStack
    desc: Follow QuantStack on Twitter

  - icon: github
    url: https://github.com/QuantStack
    desc: Follow QuantStack on GitHub

  - icon: linkedin
    url: https://www.linkedin.com/company/quantstack
    desc: Follow QuantStack on Linkedin

people:
  SylvainCorlay:
    name: Sylvain Corlay
    avatar: 2397974
    email: sylvain.corlay@gmail.com
    twitter: SylvainCorlay
    github: SylvainCorlay
    url: SylvainCorlay

  JohanMabille:
    name: Johan Mabille
    avatar: 6754742
    email: johan.mabille@gmail.com
    twitter: JohanMabille
    github: JohanMabille
    url: JohanMabille

  #WolfVollprecht:
  #  name: Wolf Vollprecht
  #  avatar: 885054
  #  email: w.vollprecht@gmail.com
  #  twitter: wuoulf 
  #  github: wolfv
  #  url: WolfVollprecht

menu:
  - title: Home
    url: /

  - title: The team
    url: /team.html

  - title: xtensor
    url: /xtensor

copyright:
  author: QuantStack
  url: http://quantstack.net
  type_title: All rights reserved
